# Generated by Django 3.0.3 on 2020-02-27 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
