# Generated by Django 3.0.3 on 2020-02-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_bookuploaddetails_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorofbook',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authorofbook',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category_id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publisher_id',
        ),
        migrations.RemoveField(
            model_name='bookuploaddetails',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='bookuploaddetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='AuthorOfBook',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='BookUploadDetails',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
