# Generated by Django 3.0.3 on 2020-02-28 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0004_auto_20200228_0611'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200, null=True)),
                ('isbn', models.CharField(max_length=100, null=True)),
                ('title', models.TextField(max_length=2000, null=True)),
                ('edition', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(max_length=5000, null=True)),
                ('published_date', models.DateField(null=True)),
                ('publisher', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='books/')),
                ('upload_date', models.DateField(null=True)),
                ('is_available', models.BooleanField(null=True)),
                ('book_format', models.CharField(choices=[('1', 'Hard-cover'), ('2', 'Paperback'), ('3', 'Printed Copy')], max_length=50, null=True)),
                ('language', models.CharField(max_length=100, null=True)),
                ('category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
