# Generated by Django 3.0.3 on 2020-02-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200228_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=100)),
                ('in_stock', models.IntegerField(default=0)),
                ('is_out_of_stock', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='is_stock_added',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
