# Generated by Django 3.0.3 on 2020-02-24 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_no', models.CharField(max_length=10)),
                ('mobile_no_verified', models.BooleanField()),
                ('email_verified', models.BooleanField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='profile_pics')),
                ('city', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('1', 'Student'), ('2', 'Alumni'), ('3', 'Faculty')], default='1', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
