# Generated by Django 3.0.3 on 2020-02-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='email_verified',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='mobile_no_verified',
            field=models.BooleanField(null=True),
        ),
    ]
